### ISSUE TITLE
졸업설계 3주차 진행

### ISSUE THREAD

**Issue by hyunjune-lee** [limitless-study/limitless-backend#2]
## 졸얼설계 3주차 계획
> `3.14 ~ 3.20`

## TODO
- [ ] Cardset 아래에 Card와 Cardset을 관리하도록, 트리구조로 관리할 수 있도록 -> 합성(복합)패턴 적용시키기
- [ ] 기본 홈 화면(트리형 노트 구조 형식으로)에 띄어주도록 api 설계하기
- [ ] 플래시 카드 생성/저장/편집 api 프론트엔드와 연동 시키기
